baseURL = "https://card-africa.netlify.app/"
relativeURLs = false   # 必须为false
canonifyURLs = true    # 推荐为true
languageCode = "en-us"
title = "CardAfrica"
theme = "introduction"

[module]
[[module.mounts]]
source = "static"
target = "static"
[[module.mounts]]
source = "themes/introduction/static"
target = "static"  # 将主题静态文件合并到主站点

[params]
whatsapp = "2348123456789"  # 替换为实际WhatsApp号码
email = "contact@cardafrica.com"
phone = "+234 812 345 6789"
address = "Lagos, Nigeria"

[markup.goldmark.renderer]
unsafe = true  # 允许原始HTML渲染

[languages]
[languages.en]
weight = 1
languageName = "English"

[languages.en.params]
slogan = "Instant Gift Card Exchange"

# 添加资产管道配置
[build]
writeStats = true  # 生成资源映射

[assets]
[assets.postcss]
noMap = false   # 启用 source map